---

- hosts: all
  become: yes

  tasks:

    - name: download a file from git repo
      get_url:
        url: https://raw.githubusercontent.com/jibinjose087/demorepo/master/demorepo-master.zip
        dest: /tmp/demorepo-master.zip
        force: yes
