---
- name: GET check
  hosts: all
  become: true
  vars:
    job_template_id: 18
 
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://18.216.19.92/api/v2/settings/changed/
        method: GET
        owner: ansible
        group: ansible
        mode: "755"
        user: admin
        password: ansible@123
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        body_format: json
        register: get_check

    - name: echo the timestamp
      command: echo ${get_check.stdout}
