---
- name: POST check
  hosts: all
  become: true
  vars:
    job_template_id: 18
 
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://18.216.19.92/api/v1/job_templates/18/launch/
        method: POST
        user: admin
        password: ansible@123
        force_basic_auth: yes
        validate_certs: no
      #  status_code: 204
        body_format: json
