---
- name: GET check
  hosts: all
  become: true
  vars:
    job_template_id: 18
 
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://18.216.19.92/api/v2/job_templates/18/launch/
        method: GET
        HEADER_Content-Type: "application/json"
        status_code: 204
        user: admin
        password: ansible@123
        force_basic_auth: yes
        validate_certs: no
        body_format: json
