---
- name: GET check
  hosts: all
  become: true
  vars:
    job_template_id: 18
 
  tasks:
    - name: Invoke download Job job_templates
      uri:
        url: https://172.31.3.71/api/v2/job_templates/18/launch/
        method: GET
  #      url: https://172.31.3.71/api/v2/job_templates/18/launch/
  #      method: POST
        owner: ansible
        group: ansible
        mode: "755"
        user: admin
        password: ansible@123
        force_basic_auth: yes
        validate_certs: no
        status_code: 202
        body_format: json
